[Patch] Improving eos home directory creation
- Script updated to last version
- EOS settings are now passed as argument rather than being hardcoded

diff --git a/cernbox_utils/eos-configure-user-directory b/cernbox_utils/eos-configure-user-directory
--- a/cernbox_utils/eos-configure-user-directory
+++ b/cernbox_utils/eos-configure-user-directory
@@ -1,6 +1,16 @@
+#!/bin/sh
+
 # WARNING: THIS VERY SCRIPT IS USED BY HUGO ON OWNCLOUD SERVER BACKEND!
 
-usr=$1
+if [ "$#" -ne 4 ]; then
+	echo "illegal number of parameters"
+	echo "syntax: eos-create-user-directory <eos_mgm_url> <eos_user_dir_prefix> <eos_recycle_dir_prefix> <user_id>"
+	echo "example:eos-create-user-directory root://eosbackup.cern.ch /eos/scratch/user /eos/scratch/user/proc/recycle <user_id>"
+	exit 1
+fi
+
+
+usr=$4
 
 if [ x$usr == x ]; then
    echo missing user
@@ -8,12 +18,9 @@ if [ x$usr == x ]; then
    exit 1
 fi
 
-export EOS_MGM_URL=root://eosbackup.cern.ch
-STORAGE_PREFIX=/eos/scratch/user
-
-#This is bogus!! it sould be something like eos recycle add bin...
-#RECYCLE_BIN=/eos/scratch/user/proc/recycle
-
+export EOS_MGM_URL=$1
+STORAGE_PREFIX=$2
+RECYCLE_BIN=$3
 
 #FIXME: protect from local users, root included
 
@@ -24,9 +31,9 @@ id $usr || (echo "ERROR resolving user" $usr; exit -1)
 
 group=`id -gn $usr`
 
-if [ $? -ne 0 ] ; then
-    echo "ERROR: cannot retrieve group name for the user" $usr;
-    exit -1
+if [ $? -ne 0 ] ; then 
+    echo "ERROR: cannot retrieve group name for the user" $usr; 
+    exit -1 
 fi
 
 homedir=${STORAGE_PREFIX}/$initial/$usr
@@ -42,17 +49,10 @@ eos -b -r 0 0 attr -r set sys.mtime.propagation="1" $homedir
 eos -b -r 0 0 attr -r set sys.forced.atomic="1" $homedir
 eos -b -r 0 0 attr -r set sys.versioning="10" $homedir
 
-eos -b -r 0 0 attr -r set sys.owner.auth="*" $homedir
-eos -b -r 0 0 attr -r set sys.forced.maxsize="10000000000" $homedir
-
 eos -b -r 0 0 quota set -u $usr -v 2TB -i 1M -p ${STORAGE_PREFIX}
 
-# DO NOT RUN IN PPS
-###eos -b -r 0 0 access allow user $usr # this is temporary until we allow all users enter in
-# but run this in eosbackup
-eos -b -r 0 0 access allow user $usr
+eos -b -r 0 0 access allow user $usr # this is temporary until we allow all users enter in
 
-#FIXME
 #eos -b -r 0 0 attr -r set sys.recycle="$RECYCLE_BIN" $homedir
 
 #eos -b -r 0 0 attr -r rm sys.eval.useracl $homedir
@@ -60,3 +60,5 @@ eos -b -r 0 0 access allow user $usr
 #set +o verbose
 
 #echo 'SUCCESS' $homedir 'created and ownership set to' $usr:$group
+
+# DONE.
